Added Set Dev Team ID section to workflow to change the project.pbxproj file

diff --git a/.github/workflows/ios_distribution.yml b/.github/workflows/ios_distribution.yml
--- a/.github/workflows/ios_distribution.yml
+++ b/.github/workflows/ios_distribution.yml
@@ -50,6 +50,26 @@ jobs:
     - name: Install Fastlane
       run: sudo gem install fastlane -NV
 
+    - name: Set Development Team ID
+      run: |
+        #!/bin/bash
+        set -e
+
+        DEVELOPMENT_TEAM_ID=${{ secrets.DEVELOPMENT_TEAM_ID }}
+        PROJECT_FILE_PATH="Code/frontend/ios/App/App.xcodeproj/project.pbxproj"
+
+        if [ -z "$DEVELOPMENT_TEAM_ID" ]; then
+          echo "Development Team ID is required"
+          exit 1
+        fi
+
+        # Use sed to set the development team ID in the project file
+        sed -i '' "s/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM_ID;/g" $PROJECT_FILE_PATH
+        sed -i '' "s/DevelopmentTeam = .*;/DevelopmentTeam = $DEVELOPMENT_TEAM_ID;/g" $PROJECT_FILE_PATH
+
+        echo "Set DEVELOPMENT_TEAM to $DEVELOPMENT_TEAM_ID in $PROJECT_FILE_PATH"
+      shell: bash
+
     - name: Build and sign iOS App
       run: |
         echo "API_KEY_ID is set to: ${API_KEY_ID:0:4}***"
